### ISSUE TITLE
About the TIME_SLICE

### ISSUE THREAD

**Issue by JackNwsuaf** [Sunlcy/Simulation_of_Process_Secheduling#1]
Can you tell me in details why ?https://github.com/Sunlcy/Simulation_of_Process_Secheduling/blob/master/main.c#L242
@Sunlcy 

```
   remainder = p->reqtime % TIME_SLICE;
            if ((p->reqtime - p->runtime) == remainder)
            {
                p->runtime += remainder;
            }
            else
            {
                p->runtime += TIME_SLICE;
            }
```

**Comment by Fibird** [comment]
First,you can get the remainder using `remainder = p->reqtime % TIME_SLICE;`, and then when the difference between `runtime` and `reqtime`, `runtime` pluses the remainder instead of `TIME_SLICE`.For example, if the `reqtime` is 9, and the `TIME_SILICE` is 2, you can easily compute the `remainder` is 1.When the `runtime` arrives 8, it must plus the `remainder` 1 instead of `TIME_SLICE` 2.
